name: _job_upload

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  upload:
    name: Upload ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.name }} 
          path: ./upload_dir

      - name: Upload to Release
        shell: bash
        run: |
          gh release upload ${{ inputs.version }} ./upload_dir/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
