name: Build dwproton 11.0-1 ARM64 (4K Paging) Fixed UID

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: 'dwproton/11.0-1'
          submodules: recursive
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Build dwproton
        run: |
          export LDFLAGS="-Wl,-z,common-page-size=4096 -Wl,-z,max-page-size=4096"
          export CROSS_LDFLAGS="-Wl,-z,max-page-size=4096"

          sed -i 's/exit 1/echo "Skipping UID check"; break/g' configure.sh
          
          mkdir -p build && cd build
          
          ../configure.sh \
            --build-name="dwproton-11-asahi-4k" \
            --target-arch=arm64 \
            --container-engine=docker \
            --docker-opts="--platform linux/arm64" \
            --relabel-volumes \
            --without-tts

          make -j$(nproc) redist

      - name: Package Result
        run: |
          tar -czvf dwproton-11.0-1-arm64-4k.tar.gz -C build/redist .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dwproton-11.0-1-arm64-4k
          path: dwproton-11.0-1-arm64-4k.tar.gz
